# Spring Properties
spring:
  application:
     name: web-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 8888   # HTTP (Tomcat) port
  
#spring.view.prefix: /main/resources/templates/
#spring.view.suffix: .jsp